// In this file will define Action Types

export const ALL_RESTARANTS_REQUEST = "ALL_RESTARANTS_REQUEST";
export const ALL_RESTARANTS_SUCCESS = "ALL_RESTARANTS_SUCCESS";
export const ALL_RESTARANTS_FAIL = "ALL_RESTARANTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SORT_BY_RATINGS = "SORT_BY_RATINGS";
export const SORT_BY_REVIWS = "SORT_BY_REVIWS";
export const TOGGLE_VEG_ONLY = "TOGGLE_VEG_ONLY";