// In This file will define action type
export const ALL_RESTAURANTS_REQUEST = "ALL_RESTAURANTS_REQUEST";
export const ALL_RESTAURANTS_SUCCESS = "ALL_RESTAURANTS_SUCCESS";
export const ALL_RESTAURANTS_FAIL = "ALL_RESTAURANTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SORT_BY_RATING = "SORT_BY_RATING";
export const SORT_BY_REVIEW = "SORT_BY_REVIEWS";
export const TOGGLE_VEG_ONLY = "TOGGLE_VEG_ONLY";
